### PR TITLE
fix: npm package name in README

### LINKED ISSUE #677: Wrong NPM package in README?
Shouldn't it be `npm install @google-cloud/dialogflow`?
With the current name I get the error `sessionClient.projectAgentSessionPath is not a function`.
See also https://stackoverflow.com/questions/63177431/node-and-dialogflow-error-unhandledpromiserejectionwarning-typeerror-sessionc.

Cheers,
Ricky

### PR DESCRIPTION
**Pull request by RiccardoCalvi**
It was still the old one, see for example https://stackoverflow.com/questions/63177431/node-and-dialogflow-error-unhandledpromiserejectionwarning-typeerror-sessionc and https://www.npmjs.com/package/@google-cloud/dialogflow

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-dialogflow/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #677 🦕

### CODE REVIEW

**Comment by RiccardoCalvi** [comment]
@googlebot I signed it!

**Comment by bcoe** [comment]
@RiccardoCalvi thank you for the patch 👍 

I notice that we should also update here https://github.com/googleapis/nodejs-dialogflow/blob/master/.repo-metadata.json#L10, bother you to make this change as well and we can address this naming issue in one PR?

**Review by IlyaUmanets — APPROVED** [review]

**Comment by jadczakd** [comment]
> @RiccardoCalvi thank you for the patch 👍
> 
> I notice that we should also update here https://github.com/googleapis/nodejs-dialogflow/blob/master/.repo-metadata.json#L10, bother you to make this change as well and we can address this naming issue in one PR?

@RiccardoCalvi I think you might have missed the msg above. Friendly ping to get it in as it's still causing confusion

**Comment by laljikanjareeya** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
